---
title: "Assignment 5"
author: "yleung"
date: "February 10, 2019"
output: html_document
---

## R Libraries
```{r setup, include=FALSE}
library(XML)
library(dplyr)
library(tidyr)
library(lattice)
library(rvest)
library(ggplot2)
library(RCurl)
library(rvest)
library(stringr)
library(stringi)

library(datasets)
library(nycflights13)
```

## 1.	Data Munging , yob2016.txt 

```{r Data-Munging}
#import and read the text file data
df <- read.table("C:\\Users\\Yat\\Documents\\MSDS\\MSDS 6306 Doing Data Science\\Unit 5\\yob2016.txt", sep=";")

#Dimension of the dataframe
dim(df)
summary(df)
str(df)

#Find the name with 3Ys
#regex=y{3}
#This give the row # of that name
names.with.3Ys<-grep('y{3}',df$V1)
#convert the row index back to the value
df$V1[names.with.3Ys]

#subset to remove the line with Fionayyy
y2016 <-subset(x=df,df$V1!="Fionayyy")
dim(y2016)
```

## 2.	Data Merging , yob2015.txt 

```{r Data-Merging}
y2015<- read.table("C:\\Users\\Yat\\Documents\\MSDS\\MSDS 6306 Doing Data Science\\Unit 5\\yob2015.txt", sep=",")

#last 10 rows of y2015
tail(y2015,10)
#All male names start with Z and look like madeup names

#merge y2016 and y2015 by name 
final<-merge(y2016, y2015, by="V1")
dim(final)
```


## 3.	Data Summary  

```{r Data-Summary}
total<-data.frame(final$V3.x+final$V3.y)
final<-cbind(final$V1,final$V2.x,total)
names(final) <- c("Name", "Gender", "Total_Count")
dim(final)
#total numbers of name in the final data frame = 31641

#Sort final by total
head(arrange(final,desc(Total_Count)),10)

#Select only girl names from the top 10 list
GirlNames<-final%>%filter(Gender == "F")
GirlNames<-head(arrange(GirlNames,desc(Total_Count)),10)
Top10GirlNames<-GirlNames%>%select(Name,Total_Count)

#Write the top 10 girl names into a csv file
write.csv(Top10GirlNames, file = "Top10GirlNames.csv")
```